apiVersion: v1
kind: Service
metadata:
  name: locust-service
spec:
  type: NodePort
  selector: 
    component: master
    app.kubernetes.io/name: locust
    app.kubernetes.io/instance: locust
    load_test: example
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30089