name: nuvolaris-testing
on: push

env:
  NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
  NGROK_PASSWORD: ${{ secrets.NGROK_PASSWORD }}
  OPS_BRANCH: main

jobs:
  kubectl-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ops
        run: |
             curl -sL bit.ly/get-ops | bash
             ops -t
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          AKS_KUBE_CONFIG: op://OpenServerless/aks_kubeconfig/text
      - name: Get nodes
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: "${{ env.AKS_KUBE_CONFIG }}"
          command: get nodes
      - name: Debug Action (if requested)
        run:  .github/debugAction.sh
      - name: Wait for Debug (if requested)
        run: .github/waitIfDebug.sh
